### ISSUE TITLE
Visual Studio 2017 crashing on start up

### ISSUE THREAD

**Issue by NeilBostrom** [Microsoft/DevSkim-VisualStudio-Extension#5]
After installing this extension, I get a crash on startup of VS2017:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.DevSkim.Language.FromFileName(System.String)
   at Microsoft.DevSkim.VSExtension.SkimShim.GetLanguageList(System.String, System.String)
   at Microsoft.DevSkim.VSExtension.SkimShim.Analyze(System.String, System.String, System.String)
   at Microsoft.DevSkim.VSExtension.SkimChecker.DoUpdate()
   at Microsoft.DevSkim.VSExtension.SkimChecker.<KickUpdate>b__17_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

**Comment by rrein** [comment]
I am having the same issue. What I am noticing is that I can open up one instance of VS 2017 with a solution loaded. It seems to be, more often than not, when I attempt to load a second instance of VS 2017 that that instance of VS is crashing.

I was able to get two instances of VS up and running by starting both up without any solution loaded and then loading the solutions after both instances were up. But then if I tried to open a third instance that would fail.

I am running VS 2017 15.2. I just updated to 15.2 and installed DevSkim so I don't have any prior experience with the extension on 15.1.

**Comment by PavelBansky** [comment]
Thank you for the report. 
What languages are being used in your solutions? Is it all C#, C++ or are you using other languages?

**Comment by NeilBostrom** [comment]
All C# except for one NodeJS project.

________________________________

**Comment by PavelBansky** [comment]
Cool, I think I have identified the issue. And pushing the fix.
I'm not sure why this bug, should affect how many instances of Visual Studio are open.

**Comment by PavelBansky** [comment]
Fix published
